### ISSUE TITLE
关于模型质量分数

### ISSUE THREAD

**Issue by Dreamgang** [yangyuke001/FIIQA-PyTorch#1]
你好，请问是不是模型预测出的分数越高，表示这个图片质量越好？还有图片标签从0-199，是不是表示图片从欠曝-->过曝-->正常？？？

**Comment by yangyuke001** [comment]
@Dreamgang 
得分越高质量越好，标签0-199是人为标定的，并不是严格意义的欠曝-->过曝-->正常

**Comment by Dreamgang** [comment]
@yangyuke001 
还有个问题，标签0-199是怎么映射到0~1的scores；然后我从百度文库下载了那些数据集，他那上面的标签是0-2的，跟这个标签0-199有啥关系？谢谢哈

**Comment by yangyuke001** [comment]
@ @Dreamgang 关于怎么映射的可以参考论文 https://link.springer.com/chapter/10.1007%2F978-3-319-70090-8_59.
 另外你看到的0-2的标签是老版本的标注可以丢弃，有个新版本的几个文件命名new_XXX_list.txt

**Comment by Dreamgang** [comment]
@yangyuke001 好的，谢谢了

**Comment by yangyuke001** [comment]
@Dreamgang 
客气了

**Comment by marigoold** [comment]
> @ @Dreamgang 关于怎么映射的可以参考论文 https://link.springer.com/chapter/10.1007%2F978-3-319-70090-8_59.
> 另外你看到的0-2的标签是老版本的标注可以丢弃，有个新版本的几个文件命名new_XXX_list.txt

@yangyuke001 Hi，想请问一下新版本的label在哪里可以获取到呢？我下载了作者repo里面贴的数据集，只有一个旧版的label txt文件。
