### ISSUE TITLE
illumination transfer 开源工具

### ISSUE THREAD

**Issue by LJ0620** [yangyuke001/FIIQA-PyTorch#2]
您好，您方便提供illumination transfer 工具吗？

**Comment by yangyuke001** [comment]
> 您好，您方便提供illumination transfer 工具吗？

抱歉，能详细说说这是个什么工具么？

**Comment by rocinant** [comment]
他说的是那个制作数据集的光照模式迁移工具，你应该去原仓库找，Chen, X., Chen, M., Jin, X., Zhao, Q.: Face illumination transfer through edgepreserving ﬁlters. In: IEEE CVPR, pp. 281–287 (2011)
